### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ogladkov** [skytells-research/DeepInfant#1]
Thanks for the excellent description of the work which is awesome! 
Is it possible to share the dataset you used for train please? Cant find something similar in good quality in open sources... Or is it the full one which is in this repo?
Thanks!!

**Comment by DrHazemAli** [comment]
Thanks for the excellent description of the work, which is awesome!

Regarding the dataset, the model was trained using a combination of open-source data that are shared in the repository. Additionally, we utilized private datasets from sources that prohibit sharing the data without prior approval. Unfortunately, we're unable to distribute these private datasets. However, the open-source datasets provided should give a good starting point.

Thanks for your understanding!

**Comment by Waseem3720** [comment]
Would you like the share the Dataset Sample size which is kept Private
